@startwbs                  
*(c1)[#Orange] "Cap GC"             
**(e1)[#Orange] "ExtData"        
**(r1)[#lightgreen] Replay     
***[#Orange] Cap GC2    
****[#Orange] ExtData2
****[#lightgreen] Predictor
*****[#lightblue] GCM2                                                        
*****[#lightblue] MKIAU
****[#Orange] History2
***[#lightgreen] Digital Filter
***[#lightblue] GCM     
**(h1)[#Orange] History
@endwbs
