@startwbs                  
*[#Orange] "Cap GC" as c1             
**[#Orange] "ExtData" as e1        
**[#lightgreen] Replay     
***[#Orange] Cap GC2    
****[#Orange] ExtData2
****[#lightgreen] Predictor
*****[#lightblue] GCM2                                                        
*****[#lightblue] MKIAU
****[#Orange] History2
***[#lightgreen] Digital Filter
***[#lightblue] GCM     
**[#Orange] History
c1 --> e1
@endwbs
